Error:
    # github.com/DataDog/datadog-agent/pkg/security/model
pkg\security\model\model_windows.go:20:9: cannot use &Event literal (type *Event) as type eval.Event in return argument:
        *Event does not implement eval.Event (missing GetFieldEventType method)
pkg\security\model\utils.go:17:2: ErrStringArrayOverflow redeclared in this block
        previous declaration at pkg\security\model\errors.go:17:2